export default function Head() {
  return (
    <>
      <title>Empire Infinity</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <meta http-equiv="Content-Security-Policy" content="script-src 'none'"></meta>
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
